/* Generated by build.sh - do not edit by hand. */
(typeof self !== "undefined" ? self : globalThis).buildInfo = {
  version: "3.6.4",
  buildDate: "20260331",
  buildTime: "204549",
  buildId: "20260331_204549"
};
