/* Generated by build.sh - do not edit by hand. */
(typeof self !== "undefined" ? self : globalThis).buildInfo = {
  version: "3.3.0",
  buildDate: "20260303",
  buildTime: "121611",
  buildId: "20260303_121611"
};
