/* Generated by build.sh - do not edit by hand. */
(typeof self !== "undefined" ? self : globalThis).buildInfo = {
  version: "3.6.2",
  buildDate: "20260304",
  buildTime: "214048",
  buildId: "20260304_214048"
};
